/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.btit.gui;

import com.btit.impls.BTITRemote;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author BaoToan
 */
public class ChatWindow extends javax.swing.JInternalFrame {
    private BTITRemote btitRemote;
    /**
     * Creates new form SingleChat
     * @param btitRemote
     */
    public ChatWindow(BTITRemote btitRemote) {
        initComponents();
        this.btitRemote = btitRemote;
    }
    
    public JTextArea getTaTypedMess() {
        return taTypedMess;
    }
    
    public JButton getBtnSend() {
        return btnSend;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneShowMess = new javax.swing.JScrollPane();
        taShowMess = new javax.swing.JTextArea();
        scrollPaneTypedMess = new javax.swing.JScrollPane();
        taTypedMess = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        taShowMess.setEditable(false);
        taShowMess.setColumns(20);
        taShowMess.setRows(5);
        scrollPaneShowMess.setViewportView(taShowMess);

        taTypedMess.setColumns(20);
        taTypedMess.setRows(5);
        taTypedMess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taTypedKeypressed(evt);
            }
        });
        scrollPaneTypedMess.setViewportView(taTypedMess);

        btnSend.setText("Send");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneShowMess)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPaneTypedMess, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneShowMess, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneTypedMess, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taTypedKeypressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taTypedKeypressed
        if(evt.getKeyCode() == 13) {
            
        }
    }//GEN-LAST:event_taTypedKeypressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane scrollPaneShowMess;
    private javax.swing.JScrollPane scrollPaneTypedMess;
    private javax.swing.JTextArea taShowMess;
    private javax.swing.JTextArea taTypedMess;
    // End of variables declaration//GEN-END:variables
}
