/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.btit.gui;

import com.btit.impls.BTITRemote;
import javax.swing.JDesktopPane;

/**
 *
 * @author BaoToan
 */
public class MainGUI extends javax.swing.JFrame {

    private BTITRemote btitRemote;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);

        btitRemote = new BTITRemote(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new com.btit.gui.DesktopPane();
        mnBar = new javax.swing.JMenuBar();
        mnMode = new javax.swing.JMenu();
        mnClientMode = new javax.swing.JMenuItem();
        mnServerMode = new javax.swing.JMenuItem();
        mnDisConnect = new javax.swing.JMenuItem();
        mnFuncs = new javax.swing.JMenu();
        mnChat = new javax.swing.JMenuItem();
        mnVoice = new javax.swing.JMenu();
        mnEnableVoice = new javax.swing.JRadioButtonMenuItem();
        mnDisableVoice = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BTITR");

        mnMode.setText("Remote");

        mnClientMode.setText("Connect to...");
        mnClientMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientModeActionPerformed(evt);
            }
        });
        mnMode.add(mnClientMode);

        mnServerMode.setText("Create server");
        mnServerMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServerModeActionPerformed(evt);
            }
        });
        mnMode.add(mnServerMode);

        mnDisConnect.setText("Disconnect");
        mnDisConnect.setEnabled(false);
        mnDisConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDisConnectActionPerformed(evt);
            }
        });
        mnMode.add(mnDisConnect);

        mnBar.add(mnMode);

        mnFuncs.setText("Funcs");

        mnChat.setText("Chat");
        mnChat.setEnabled(false);
        mnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChatActionPerformed(evt);
            }
        });
        mnFuncs.add(mnChat);

        mnBar.add(mnFuncs);

        mnVoice.setText("Voice");

        mnEnableVoice.setSelected(true);
        mnEnableVoice.setText("Enable");
        mnEnableVoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEnableVoiceActionPerformed(evt);
            }
        });
        mnVoice.add(mnEnableVoice);

        mnDisableVoice.setText("Disable");
        mnDisableVoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDisableVoiceActionPerformed(evt);
            }
        });
        mnVoice.add(mnDisableVoice);

        mnBar.add(mnVoice);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        setBounds(0, 0, 632, 431);
    }// </editor-fold>//GEN-END:initComponents

    private void mnClientModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientModeActionPerformed
        ConnectDialog connectDialog = new ConnectDialog(this, true);
        connectDialog.setVisible(true);
    }//GEN-LAST:event_mnClientModeActionPerformed

    private void mnServerModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServerModeActionPerformed
        CreateServerDialog crServer = new CreateServerDialog(this, true);
        crServer.setVisible(true);
    }//GEN-LAST:event_mnServerModeActionPerformed

    private void mnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChatActionPerformed
        BTITRemote.chatWindow.setVisible(true);
    }//GEN-LAST:event_mnChatActionPerformed

    private void mnDisConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDisConnectActionPerformed
        btitRemote = new BTITRemote(this);
        established(false);
    }//GEN-LAST:event_mnDisConnectActionPerformed

    private void mnEnableVoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEnableVoiceActionPerformed
        btitRemote.enableSound(true);
        mnDisableVoice.setSelected(false);
        mnEnableVoice.setSelected(true);
    }//GEN-LAST:event_mnEnableVoiceActionPerformed

    private void mnDisableVoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDisableVoiceActionPerformed
        btitRemote.enableSound(false);
        mnDisableVoice.setSelected(true);
        mnEnableVoice.setSelected(false);
    }//GEN-LAST:event_mnDisableVoiceActionPerformed

    public void established(boolean established) {
        mnClientMode.setEnabled(!established);
        mnServerMode.setEnabled(!established);
        mnDisConnect.setEnabled(established);
        mnChat.setEnabled(established);
    }

    public JDesktopPane getDesktopPanel() {
        return desktopPanel;
    }

    public BTITRemote getBTITRemote() {
        return btitRemote;
    }

    public void setBtitRemote(BTITRemote btitRemote) {
        this.btitRemote = btitRemote;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.btit.gui.DesktopPane desktopPanel;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mnChat;
    private javax.swing.JMenuItem mnClientMode;
    private javax.swing.JMenuItem mnDisConnect;
    private javax.swing.JRadioButtonMenuItem mnDisableVoice;
    private javax.swing.JRadioButtonMenuItem mnEnableVoice;
    private javax.swing.JMenu mnFuncs;
    private javax.swing.JMenu mnMode;
    private javax.swing.JMenuItem mnServerMode;
    private javax.swing.JMenu mnVoice;
    // End of variables declaration//GEN-END:variables
}
