/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.btit.init;

import com.btit.gui.ConnectDialog;
import com.btit.gui.CreateServerDialog;
import com.btit.gui.DesktopPanel;
import com.btit.impls.BTITRemote;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author BaoToan
 */
public class MainGUI extends javax.swing.JFrame {

    private BTITRemote btitRemote;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);

        btitRemote = new BTITRemote(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new com.btit.gui.DesktopPanel();
        mnBar = new javax.swing.JMenuBar();
        mnMode = new javax.swing.JMenu();
        mnClientMode = new javax.swing.JMenuItem();
        mnServerMode = new javax.swing.JMenuItem();
        mnDisConnect = new javax.swing.JMenuItem();
        mnFuncs = new javax.swing.JMenu();
        mnChat = new javax.swing.JMenuItem();
        mnFileTrans = new javax.swing.JMenuItem();
        mnVoice = new javax.swing.JMenu();
        mnEnableVoice = new javax.swing.JRadioButtonMenuItem();
        mnDisableVoice = new javax.swing.JRadioButtonMenuItem();
        mnOption = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BTITR");

        mnMode.setText("Remote");

        mnClientMode.setText("Connect to...");
        mnClientMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientModeActionPerformed(evt);
            }
        });
        mnMode.add(mnClientMode);

        mnServerMode.setText("Create server");
        mnServerMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnServerModeActionPerformed(evt);
            }
        });
        mnMode.add(mnServerMode);

        mnDisConnect.setText("Disconnect");
        mnDisConnect.setEnabled(false);
        mnDisConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDisConnectActionPerformed(evt);
            }
        });
        mnMode.add(mnDisConnect);

        mnBar.add(mnMode);

        mnFuncs.setText("Funcs");

        mnChat.setText("Chat");
        mnChat.setEnabled(false);
        mnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChatActionPerformed(evt);
            }
        });
        mnFuncs.add(mnChat);

        mnFileTrans.setText("File transfer");
        mnFuncs.add(mnFileTrans);

        mnBar.add(mnFuncs);

        mnVoice.setText("Voice");

        mnEnableVoice.setSelected(true);
        mnEnableVoice.setText("Enable");
        mnVoice.add(mnEnableVoice);

        mnDisableVoice.setText("Disable");
        mnVoice.add(mnDisableVoice);

        mnBar.add(mnVoice);

        mnOption.setText("Opts");

        jMenuItem1.setText("Change password");
        mnOption.add(jMenuItem1);

        jMenuItem2.setText("Change port");
        mnOption.add(jMenuItem2);

        mnBar.add(mnOption);

        setJMenuBar(mnBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        setBounds(0, 0, 632, 431);
    }// </editor-fold>//GEN-END:initComponents

    private void mnClientModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientModeActionPerformed
        ConnectDialog connectDialog = new ConnectDialog(this, true);
        connectDialog.setVisible(true);
    }//GEN-LAST:event_mnClientModeActionPerformed

    private void mnServerModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnServerModeActionPerformed
        CreateServerDialog crServer = new CreateServerDialog(this, true);
        crServer.setVisible(true);
    }//GEN-LAST:event_mnServerModeActionPerformed

    private void mnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChatActionPerformed
        if(btitRemote.isEstablished()) {
            BTITRemote.chatWindow.setVisible(true);
        }
    }//GEN-LAST:event_mnChatActionPerformed

    private void mnDisConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDisConnectActionPerformed
        try {
            if (null != btitRemote.getSocket() && !btitRemote.getSocket().isClosed()) {
                btitRemote.getSocket().close();
            }
            if (null != btitRemote.getServerSocket() && !btitRemote.getServerSocket().isClosed()) {
                btitRemote.getServerSocket().close();
            }
            if (null != btitRemote.getSocketPool() && !btitRemote.getSocketPool().isShutdown()) {
                btitRemote.getSocketPool().shutdown();
            }
            setTitle("BTITR");
            established(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "An error occurred! Please contact to baotoan.95@gmail.com", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mnDisConnectActionPerformed

    public void established(boolean established) {
        mnClientMode.setEnabled(!established);
        mnServerMode.setEnabled(!established);
        mnDisConnect.setEnabled(established);
        mnChat.setEnabled(established);
    }

    public DesktopPanel getDesktopPanel() {
        return desktopPanel;
    }

    public BTITRemote getBTITRemote() {
        return btitRemote;
    }

    public void setBtitRemote(BTITRemote btitRemote) {
        this.btitRemote = btitRemote;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.btit.gui.DesktopPanel desktopPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar mnBar;
    private javax.swing.JMenuItem mnChat;
    private javax.swing.JMenuItem mnClientMode;
    private javax.swing.JMenuItem mnDisConnect;
    private javax.swing.JRadioButtonMenuItem mnDisableVoice;
    private javax.swing.JRadioButtonMenuItem mnEnableVoice;
    private javax.swing.JMenuItem mnFileTrans;
    private javax.swing.JMenu mnFuncs;
    private javax.swing.JMenu mnMode;
    private javax.swing.JMenu mnOption;
    private javax.swing.JMenuItem mnServerMode;
    private javax.swing.JMenu mnVoice;
    // End of variables declaration//GEN-END:variables
}
